server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: 'amigoscode'
    url: jdbc:postgresql://localhost:5432/customer
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

rabbitmq:
  queue:
    name: customer-notification-queue
  exchange:
    name: customer-notification-exchange
  routingKey:
    name: customer-notification-key
